import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.scss'
import Header from '@/components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Bakery Leaderboard</title>
        <meta name="description" content="Leaderboard and ranked stat tracking for Bakery server"></meta>
      </head>
      <body className={inter.className}>
        <Header />
        <main className="app">
          {children}
        </main>
      </body>
    </html>
  )
}
